networks:
  localenv:
    driver: bridge

services:
  postgres:
    container_name: waika_project_postgres
    image: postgres:17
    restart: always
    shm_size: 128mb
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - ../.env
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - localenv
