networks:
  localenv:
    driver: bridge

services:
  adminer:
    container_name: waika_project_adminer
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
    networks:
      - localenv
