networks:
  localenv:
    driver: bridge

services:
  nginx:
    container_name: waika_project_nginx
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile.nginx
    depends_on:
      - ssr 
      - server 
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./nginx/includes/:/etc/nginx/includes/:ro
    networks:
      - localenv

  ssr:
    container_name: waika_project_ssr
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile.ssr
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    env_file:
      - ../.env
    volumes:
      - ../packages/client/:/packages/client/:ro
    networks:
      - localenv